// packages/create-plugma/templates/examples/widget-blank-w-ui/src/ui/[framework=="svelte"]/App.svelte
<script lang="ts">
	import svelteLogo from "./assets/svelte.svg";
	import Icon from "./components/Icon.svelte";
</script>

<div class="container">
	<div class="banner">
		<Icon svg="plugma" size={38} />

		<Icon svg="plus" size={24} />

		<img src={svelteLogo} width="44" height="44" alt="Svelte logo" />
	</div>
</div>

<style>
	.container {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100%;
		width: 100%;
		flex-direction: column;
	}
	.banner {
		display: flex;
		align-items: center;
		gap: 18px;
		margin-bottom: 16px;
	}
</style>

// packages/create-plugma/templates/examples/blank-plugin-w-ui/src/ui/[framework=="react"]/App.tsx
import React from "react";
import reactLogo from "./assets/react.svg";
import Icon from "./components/Icon";

const App: React.FC = () => {
	const styles = {
		container: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			height: "100%",
			width: "100%",
			flexDirection: "column" as const,
		},
		banner: {
			display: "flex",
			alignItems: "center",
			gap: "18px",
			marginBottom: "16px",
		},
		nodeCount: {
			fontSize: "11px",
		}
	};

	return (
		<div style={styles.container}>
			<div style={styles.banner}>
				<Icon svg="plugma" size={38} />
				<Icon svg="plus" size={24} />
				<img src={reactLogo} width="44" height="44" alt="Svelte logo" />
			</div>
		</div>
	);
};

export default App;
