// packages/create-plugma/templates/frameworks/svelte/components/Button.svelte
<script lang="ts">
	let { children, href, target, style, onclick } = $props();
</script>

{#if href}
	<a class="Button" {href} {target} {style} {onclick}>{@render children()}</a>
{:else}
	<button class="Button" {style} {onclick}>
		{@render children()}
	</button>
{/if}

<style>
	.Button {
		display: block;
		border-radius: 5px;
		border: 1px solid var(--figma-color-border);
		padding: 0 7px;
		line-height: 22px;
		text-decoration: none;
		color: var(--figma-color-text);
	}
</style>

// packages/create-plugma/templates/vue/src/components/Button.vue
<script>
export default {
	name: 'Button',
	props: {
		href: {
			default: null,
		},
		target: {
			default: null,
		},
		style: {
			default: () => ({}),
		},
		onClick: {
			default: null,
		},
	},
	methods: {
		handleClick(event) {
			if (this.onClick) {
				this.onClick(event);
			}
		},
	},
};
</script>

<template>
	<div>
		<a v-if="href" :class="'Button'" :href="href" :target="target" :style="style" @click="handleClick">
			<slot />
		</a>
		<button v-else :class="'Button'" :style="style" @click="handleClick">
			<slot />
		</button>
	</div>
</template>

<style scoped>
.Button {
	display: block;
	border-radius: 5px;
	border: 1px solid var(--figma-color-border);
	padding: 0 7px;
	line-height: 22px;
	text-decoration: none;
	color: var(--figma-color-text);
}
</style>
