// sandbox-bkp/src/App.svelte
<script lang="ts">
	import svelteLogo from './assets/svelte.svg'
	import Icon from './components/Icon.svelte'
	import Input from './components/Input.svelte'
	import Button from './components/Button.svelte'

	function createRectangles(count: number) {
		parent.postMessage(
			{
				pluginMessage: {
					type: 'CREATE_RECTANGLES',
					count,
				},
			},
			'*',
		)
	}

	let rectCount = $state(5)
	let nodeCount = $state(0)

	window.onmessage = (event) => {
		const message = event.data.pluginMessage

		if (message.type === 'POST_NODE_COUNT') {
			nodeCount = message.count
		}
	}
</script>

<div class="container">
	<div class="banner">
		<Icon svg="plugma" size={38} />

		<Icon svg="plus" size={24} />

		<img src={svelteLogo} width="44" height="44" alt="Svelte logo" />
	</div>

	<div class="field create-rectangles">
		<Input type="number" bind:value={rectCount}></Input>
		<Button onclick={() => createRectangles(rectCount)}>Create Rectangles</Button>
	</div>
	<!-- <div class="field">
		<Button onclick={runTest}>Run Test</Button>
	</div>
	{#if testResults.length > 0}
		<div class="test-results">
			{#each testResults as result}
				<div class="test-assertion">
					<span class="value">{result[0][1][0]}</span>
					<span class="operator">{result[1][0]}</span>
					<span class="operator">{result[2][0]}</span>
					<span class="expected">{result[2][1][0]}</span>
				</div>
			{/each}
		</div>
	{/if}
	 -->
	<div class="field node-count">
		<span>{nodeCount} nodes selected</span>
	</div>
</div>

<style>
	.container {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100%;
		width: 100%;
		flex-direction: column;
	}
	.banner {
		display: flex;
		align-items: center;
		gap: 18px;
		margin-bottom: 16px;
	}

	.node-count {
		font-size: 11px;
	}

	.field {
		display: flex;
		gap: var(--spacer-2);
		height: var(--spacer-5);
		align-items: center;
	}

	.create-rectangles :global(.Input) {
		width: 40px;
	}

	.test-results {
		margin-top: var(--spacer-3);
		font-size: 11px;
		display: flex;
		flex-direction: column;
		gap: var(--spacer-1);
		padding: var(--spacer-2);
		background: var(--figma-color-bg-secondary);
		border-radius: 6px;
	}

	.test-assertion {
		color: var(--figma-color-text);
		display: flex;
		gap: var(--spacer-1);
	}

	.test-assertion .value {
		color: var(--figma-color-text-secondary);
	}

	.test-assertion .operator {
		color: var(--figma-color-text-tertiary);
	}

	.test-assertion .expected {
		color: var(--figma-color-text-brand);
	}
</style>

// packages/create-plugma/templates/examples/rectangle-creator/src/ui/[framework=="vue"]/App.vue
<script lang="ts">
import { ref } from 'vue'
import Icon from './components/Icon.vue'
import Input from './components/Input.vue'
import Button from './components/Button.vue'

export default {
	components: {
		Icon,
		Input,
		Button
	},
	setup() {
		// Reactive state using Vue's ref
		const rectCount = ref(5)
		const nodeCount = ref(0)

		// Function to create rectangles
		function createRectangles(count) {
			parent.postMessage(
				{
					pluginMessage: {
						type: 'CREATE_RECTANGLES',
						count,
					},
				},
				'*',
			)
		}

		// Message listener to update node count
		window.onmessage = (event) => {
			const message = event.data.pluginMessage
			if (message.type === 'POST_NODE_COUNT') {
				nodeCount.value = message.count
			}
		}

		// Return reactive variables and methods to the template
		return {
			rectCount,
			nodeCount,
			createRectangles,
		}
	}
}
</script>

<template>
	<div class="container">
		<div class="banner">
			<Icon :svg="'plugma'" :size="38" />
			<Icon :svg="'plus'" :size="24" />
			<img src="./assets/vue.svg" width="44" height="44" alt="Vue logo" />
		</div>

		<div class="field create-rectangles">
			<Input v-model="rectCount" type="number" />
			<Button @click="createRectangles(rectCount)">Create Rectangles</Button>
		</div>

		<div class="field node-count">
			<span>{{ nodeCount }} nodes selected</span>
		</div>
	</div>
</template>

<style scoped>
.container {
	display: flex;
	align-items: center;
	justify-content: center;
	height: 100%;
	width: 100%;
	flex-direction: column;
}

.banner {
	display: flex;
	align-items: center;
	gap: 18px;
	margin-bottom: 16px;
}

.node-count {
	font-size: 11px;
}

.field {
	display: flex;
	gap: var(--spacer-2);
	height: var(--spacer-5);
	align-items: center;
}

.create-rectangles .Input {
	width: 40px;
}
</style>
