// packages/create-plugma/templates/vue-ts/src/components/Button.vue
<script lang="ts">
import { defineComponent, PropType } from 'vue'

export default defineComponent({
	name: 'Button',
	props: {
		href: {
			default: null
		},
		target: {
			default: '_self'
		},
		style: {
			default: null
		},
		onclick: {
			default: null
		}
	}
})
</script>

<template>
	<component :is="href ? 'a' : 'button'" class="Button" :href="href" :target="target" :style="style"
		:onclick="onclick">
		<slot />
	</component>
</template>

<style scoped>
.Button {
	display: block;
	border-radius: 5px;
	border: 1px solid var(--figma-color-border);
	padding: 0 7px;
	line-height: 22px;
	text-decoration: none;
	color: var(--figma-color-text);
}
</style>

// packages/create-plugma/templates/frameworks/svelte/components/Button.svelte
<script lang="ts">
	let { children, href, target, style, onclick } = $props();
</script>

{#if href}
	<a class="Button" {href} {target} {style} {onclick}>{@render children()}</a>
{:else}
	<button class="Button" {style} {onclick}>
		{@render children()}
	</button>
{/if}

<style>
	.Button {
		display: block;
		border-radius: 5px;
		border: 1px solid var(--figma-color-border);
		padding: 0 7px;
		line-height: 22px;
		text-decoration: none;
		color: var(--figma-color-text);
	}
</style>
